# -*- coding: utf-8 -*-
"""test try 2 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150ULAmUsKBuWLRkkvyViG2GuFe5R9z9M
"""

# imports
import os
import shutil
import yaml
import kagglehub
from ultralytics import YOLO
from tqdm import tqdm  # For progress bars

# install dependancies
print("Installing Ultralytics and Kagglehub")
#!pip install ultralytics kagglehub -q
print ("install worked")

# datasets
print("\n⬇ Downloading Datasets")
try:
    # Dataset 1 regular fish
    fish_dataset_path = kagglehub.dataset_download('zehraatlgan/fish-detection')


    # Dataset 2 which has the jellyfish
    jelly_dataset_path = kagglehub.dataset_download('akshatsng/underwater-dataset-for-8-classes-with-label')


except Exception as e:
    print("error no  Kagggle.Json")
    if os.path.exists("test_try_2_ipynb.py/kaggle.json"):
        print("Found kaggle.json, moving to /root/.kaggle/...")
        os.makedirs("/root/.kaggle/", exist_ok=True)
        shutil.copy("https://sites.lafayette.edu/ece414-fa24-finalproject/kaggle.json", "/root/.kaggle/kaggle.json")
        os.chmod("/root/.kaggle/kaggle.json", 600)
        print("Please re-run this cell.")
    raise e

# put the 2 together
base_dir = 'merged_dataset'
if os.path.exists(base_dir): shutil.rmtree(base_dir)

dirs_to_make = [
    'train/images', 'train/labels',
    'valid/images', 'valid/labels',
    'test/images', 'test/labels'
]

for d in dirs_to_make:
    os.makedirs(os.path.join(base_dir, d), exist_ok=True)


# continued merging the dataset
def merge_dataset(source_root, subset_name, is_jelly_dataset=False):

    """

    Copies images and labels from source to the merged directory.

    """

    img_src = None

    lbl_src = None

   

    # First, try common structures

    possible_paths = [

        # Structure 1: root/subset_name/images

        (os.path.join(source_root, subset_name, 'images'),

         os.path.join(source_root, subset_name, 'labels')),

        # Structure 2: root/images/subset_name

        (os.path.join(source_root, 'images', subset_name),

         os.path.join(source_root, 'labels', subset_name)),

        # Structure 3: root/subset_name (direct)

        (os.path.join(source_root, subset_name),

         os.path.join(source_root, subset_name))

    ]

   

    for img_path, lbl_path in possible_paths:

        if os.path.exists(img_path):

            img_src = img_path

            if os.path.exists(lbl_path):

                lbl_src = lbl_path

            else:

                # Try to find labels in a different location

                for root, dirs, files in os.walk(source_root):

                    if 'labels' in dirs:

                        lbl_src = os.path.join(root, 'labels')

                        if subset_name in os.listdir(lbl_src):

                            lbl_src = os.path.join(lbl_src, subset_name)

                        break

            break

   

    if not img_src or not os.path.exists(img_src):

        print(f"Warning: Could not find {subset_name} images in {source_root}")

        return

   

    # Destination paths

    img_dst = os.path.join(base_dir, subset_name, 'images')

    lbl_dst = os.path.join(base_dir, subset_name, 'labels')

   

    print(f"   Processing {subset_name} from {'Jellyfish' if is_jelly_dataset else 'Fish'} dataset...")

   

    files = [f for f in os.listdir(img_src) if f.endswith(('.jpg', '.jpeg', '.png'))]

   

    if not files:

        print(f"   No images found in {img_src}")

        return

   

    count = 0

    jellyfish_count = 0

   

    for file in tqdm(files, desc=f"Merging {subset_name}", leave=False):

        base_name = os.path.splitext(file)[0]

        label_file = base_name + '.txt'

        src_label_path = os.path.join(lbl_src, label_file) if lbl_src and os.path.exists(lbl_src) else None

       

        if is_jelly_dataset:

            # For jellyfish dataset

            prefix = "jelly_"

            dst_img_name = prefix + file

            dst_label_name = (prefix + label_file)

           

            # Always copy the image

            shutil.copy(os.path.join(img_src, file), os.path.join(img_dst, dst_img_name))

           

            if src_label_path and os.path.exists(src_label_path):

                with open(src_label_path, 'r') as f:

                    lines = f.readlines()

               

                new_lines = []

                for line in lines:

                    parts = line.strip().split()

                    if len(parts) >= 5:

                        cls_id = int(parts[0])

                       

                        # Remap ALL classes from jellyfish dataset

                        # The jellyfish dataset has 8 classes, we need to offset them

                        # Assuming jellyfish is class 0 in the source dataset

                        if cls_id == 0:  # Jellyfish in source

                            new_cls_id = 13  # Jellyfish in merged dataset (index 13)

                            jellyfish_count += 1

                        else:

                            # Offset other classes to avoid conflicts with fish dataset

                            new_cls_id = cls_id + 14  # Start from 14 to avoid overlap

                       

                        new_line = f"{new_cls_id} {' '.join(parts[1:])}\n"

                        new_lines.append(new_lines)

               

                if new_lines:

                    with open(os.path.join(lbl_dst, dst_label_name), 'w') as f:

                        f.writelines(new_lines)

                    count += 1

                else:

                    # Create empty label file if no valid annotations

                    open(os.path.join(lbl_dst, dst_label_name), 'w').close()
                    
                    count += 1

            else:

                # Create empty label file if no label file exists
                open(os.path.join(lbl_dst, dst_label_name), 'w').close()
                count += 1

        else:

            # For regular fish dataset - copy as is

            shutil.copy(os.path.join(img_src, file), os.path.join(img_dst, file))

           

            if src_label_path and os.path.exists(src_label_path):

                shutil.copy(src_label_path, os.path.join(lbl_dst, label_file))

                count += 1

            else:

                # Create empty label file if no label exists

                open(os.path.join(lbl_dst, label_file), 'w').close()

                count += 1

   

    if is_jelly_dataset:

        print(f"   -> Added {count} images ({jellyfish_count} with jellyfish annotations).")

    else:

        print(f"   -> Added {count} images.")

 

   

 
# final merge

for split in ['train', 'valid', 'test']:
    merge_dataset(fish_dataset_path, split, is_jelly_dataset=False)


for split in ['train', 'valid', 'test']:
    merge_dataset(jelly_dataset_path, split, is_jelly_dataset=True)

# redo the yaml
class_names = [
    'AngelFish', 'BlueTang', 'ButterflyFish', 'ClownFish', 'GoldFish',
    'Gourami', 'MorishIdol', 'PlatyFish', 'RibbonedSweetlips',
    'ThreeStripedDamselfish', 'YellowCichlid', 'YellowTang', 'ZebraFish',
    'JellyFish' # Class 13
]

data_config = {
    'path': base_dir,
    'train': 'train/images',
    'val': 'valid/images',
    'test': 'test/images',
    'nc': len(class_names),
    'names': class_names
}

yaml_path = '/home/kalgaonp/Documents/chloe_ben_ryan/data_merged.yaml'
with open(yaml_path, 'w') as f:
    yaml.dump(data_config, f)

#Training time
print("starting training")
model = YOLO('yolo11n.pt')

results = model.train(
    data=yaml_path,
    epochs=40,
    imgsz=640,
    batch=16,
    project='/home/kalgaonp/Documents/chloe_ben_ryan/fish_project',
    name='merged_run',
    exist_ok=True
)

# project results on video
print("Preping video")
video_path = '/home/kalgaonp/Documents/chloe_ben_ryan/fish_project/Dream_Aquarium.mp4'

if os.path.exists(video_path):
    video_results = model.predict(
        source=video_path,
        save=True,
        conf=0.4,
        project='/home/kalgaonp/Documents/chloe_ben_ryan/fish_project',
        name='video_inference',
        exist_ok=True
    )

    output_dir = '/home/kalgaonp/Documents/chloe_ben_ryan/fish_project'
    files = [f for f in os.listdir(output_dir) if f.endswith(('.mp4', '.avi'))]

    print("-" * 50)
    if files:
        #print(Video saved at: {os.path.join(output_dir, files[0])}")
        print("Go to the 'Files' tab -> fish_project -> video_inference -> Download the video.")
    else:
        print("Processing finished, check video file path")
else:
    print("Video Path not found")
