# -*- coding: utf-8 -*-
"""test try 2 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150ULAmUsKBuWLRkkvyViG2GuFe5R9z9M
"""

# imports
import os
import shutil
import yaml
import kagglehub
from ultralytics import YOLO
from tqdm import tqdm  # For progress bars

# install dependancies
print("Installing Ultralytics and Kagglehub")
#!pip install ultralytics kagglehub -q
print ("install worked")

# datasets
print("\n⬇ Downloading Datasets")
try:
    # Dataset 1 regular fish
    fish_dataset_path = kagglehub.dataset_download('zehraatlgan/fish-detection')


    # Dataset 2 which has the jellyfish
    jelly_dataset_path = kagglehub.dataset_download('akshatsng/underwater-dataset-for-8-classes-with-label')


except Exception as e:
    print("error no  Kagggle.Json")
    if os.path.exists("test_try_2_ipynb.py/kaggle.json"):
        print("Found kaggle.json, moving to /root/.kaggle/...")
        os.makedirs("/root/.kaggle/", exist_ok=True)
        shutil.copy("https://sites.lafayette.edu/ece414-fa24-finalproject/kaggle.json", "/root/.kaggle/kaggle.json")
        os.chmod("/root/.kaggle/kaggle.json", 600)
        print("Please re-run this cell.")
    raise e

# put the 2 together
base_dir = 'merged_dataset'
if os.path.exists(base_dir): shutil.rmtree(base_dir)

dirs_to_make = [
    'train/images', 'train/labels',
    'valid/images', 'valid/labels',
    'test/images', 'test/labels'
]

for d in dirs_to_make:
    os.makedirs(os.path.join(base_dir, d), exist_ok=True)


# continued merging the dataset
def merge_dataset(source_root, subset_name, is_jelly_dataset=False):
    """
    Copies images and labels from source to the merged directory.
    """
    # Find the specific subset folder (train/valid/test)
    img_src = None
    lbl_src = None

    # handles multiple paths
    for root, dirs, files in os.walk(source_root):
        if subset_name in dirs:
            # more path stuff
            sub_path = os.path.join(root, subset_name)
            if 'images' in os.listdir(sub_path):
                img_src = os.path.join(sub_path, 'images')
                lbl_src = os.path.join(sub_path, 'labels')
            else:

                pass

        if 'images' in dirs and subset_name in os.listdir(os.path.join(root, 'images')):
             img_src = os.path.join(root, 'images', subset_name)
             lbl_src = os.path.j/home/kalgaonp/Documents/chloe_ben_ryan/fish_projectoin(root, 'labels', subset_name)


    if not img_src:

         img_src = os.path.join(source_root, subset_name, 'images')
         lbl_src = os.path.join(source_root, subset_name, 'labels')

    if not os.path.exists(img_src):
        print("error specific image didn't work getting skipped")
        return

    # Destination paths
    img_dst = os.path.join(base_dir, subset_name, 'images')
    lbl_dst = os.path.join(base_dir, subset_name, 'labels')

    print(f"   Processing {subset_name} from {'Jellyfish' if is_jelly_dataset else 'Fish'} dataset...")

    files = [f for f in os.listdir(img_src) if f.endswith(('.jpg', '.jpeg', '.png'))]

    count = 0
    for file in tqdm(files, desc=f"Merging {subset_name}", leave=False):
        base_name = os.path.splitext(file)[0]#!pip install ultralytics kagglehub -q
        label_file = base_name + '.txt'
        src_label_path = os.path.join(lbl_src, label_file)

        if os.path.exists(src_label_path):
            if is_jelly_dataset:


                with open(src_label_path, 'r') as f:
                    lines = f.readlines()

                new_lines = []
                has_jelly = False
                for line in lines:
                    parts = line.strip().split()
                    cls_id = int(parts[0])

                    if cls_id == 4:
                        new_lines.append(f"13 {' '.join(parts[1:])}\n")
                        has_jelly = True

                if has_jelly:
                    # Save image with prefix to avoid overwrite
                    shutil.copy(os.path.join(img_src, file), os.path.join(img_dst, f"jelly_{file}"))
                    # Save new label
                    with open(os.path.join(lbl_dst, f"jelly_{label_file}"), 'w') as f:
                        f.writelines(new_lines)
                    count += 1
            else:
                # take the main dataset and make a copy so they can be joined
                shutil.copy(os.path.join(img_src, file), os.path.join(img_dst, file))
                shutil.copy(src_label_path, os.path.join(lbl_dst, label_file))
                count += 1
    print(f"   -> Added {count} images.")

# final merge

for split in ['train', 'valid', 'test']:
    merge_dataset(fish_dataset_path, split, is_jelly_dataset=False)


for split in ['train', 'valid', 'test']:
    merge_dataset(jelly_dataset_path, split, is_jelly_dataset=True)

# redo the yaml
class_names = [
    'AngelFish', 'BlueTang', 'ButterflyFish', 'ClownFish', 'GoldFish',
    'Gourami', 'MorishIdol', 'PlatyFish', 'RibbonedSweetlips',
    'ThreeStripedDamselfish', 'YellowCichlid', 'YellowTang', 'ZebraFish',
    'JellyFish' # Class 13
]

data_config = {
    'path': base_dir,
    'train': 'train/images',
    'val': 'valid/images',
    'test': 'test/images',
    'nc': len(class_names),
    'names': class_names
}

yaml_path = '/home/kalgaonp/Documents/chloe_ben_ryan/data_merged.yaml'
with open(yaml_path, 'w') as f:
    yaml.dump(data_config, f)

#Training time
print("starting training")
model = YOLO('yolo11n.pt')

results = model.train(
    data=yaml_path,
    epochs=1,
    imgsz=640,
    batch=16,
    project='/home/kalgaonp/Documents/chloe_ben_ryan/fish_project',
    name='merged_run',
    exist_ok=True
)

# project results on video
print("Preping video")
video_path = '/home/kalgaonp/Documents/chloe_ben_ryan/fish_project/Dream_Aquarium.mp4'

if os.path.exists(video_path):
    video_results = model.predict(
        source=video_path,
        save=True,
        conf=0.4,
        project='/home/kalgaonp/Documents/chloe_ben_ryan/fish_project',
        name='video_inference',
        exist_ok=True
    )

    output_dir = '/home/kalgaonp/Documents/chloe_ben_ryan/fish_project'
    files = [f for f in os.listdir(output_dir) if f.endswith(('.mp4', '.avi'))]

    print("-" * 50)
    if files:
        #print(Video saved at: {os.path.join(output_dir, files[0])}")
        print("Go to the 'Files' tab -> fish_project -> video_inference -> Download the video.")
    else:
        print("Processing finished, check video file path")
else:
    print("Video Path not found")
